python : anaconda pip

pip :
	mkdir ~/.pip
	cp pip.conf ~/.pip

anaconda :
	wget https://repo.anaconda.com/archive/Anaconda2-2019.03-Linux-x86_64.sh
	bash Anaconda2-2019.03-Linux-x86_64.sh
	pip install -r requirements.txt
